# Generated by Django 5.2.7 on 2025-10-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortlink",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
