# Generated by Django 5.2.7 on 2025-10-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_shortlink_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortlink",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
