# Generated by Django 5.2.7 on 2025-10-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers_user_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
